imports:
  - { resource: ../common.yml }

services:
    block_reassurance_form_data_handler:
        class: 'Presta_Shop\Module\Block_Reassurance\Form\Psreassurance_Form_Data_Handler'
        public: true
        arguments:
            - '@block_reassurance_repository'
            - '@prestashop.core.admin.lang.repository'
            - '@doctrine.orm.default_entity_manager'