services:
  block_reassurance_repository:
    class: Presta_Shop\Module\Block_Reassurance\Repository\Psreassurance_Repository
    public: true
    arguments:
      - '@doctrine'
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'